// AUTOGENERATED

// [
//     '{{repeat(5, 7)}}',
//     {
//         _id: '{{objectId()}}',
//         guid: '{{guid()}}',
//         title: 'Department {{company().toUpperCase()}}',
//         users: {
//             _id: '{{index()}}',
//             lead: {
//                 _id: '{{index()}}',
//                 name: '{{firstName()}} {{surname()}}',
//                 email: '{{email()}}'
//             },
//             employees: [
//                 '{{repeat(5, 7)}}',
//                 {
//                     _id: '{{index()}}',
//                     name: '{{firstName()}} {{surname()}}',
//                     email: '{{email()}}'
//                 }
//             ]
//         }
//     }
// ]

export const orgStructureData: OrgDepartment =
{
    "_id": "6119436aaed50e378b8105f0",
    "guid": "35924cb2-ed31-4801-9959-c251f64d9ae0",
    "title": "Department GLUKGLUK",
    "users": {
        "_id": 0,
        "lead": {
            "_id": 0,
            "name": "Lynne Goodwin",
            "email": "lynnegoodwin@glukgluk.com"
        },
        "employees": [
            {
                "_id": 0,
                "name": "Briana Sargent",
                "email": "brianasargent@glukgluk.com"
            },
            {
                "_id": 1,
                "name": "Solomon Randolph",
                "email": "solomonrandolph@glukgluk.com"
            },
        ]
    },
    child: [{
        "_id": "6119436ad18591b22ff48a2d",
        "guid": "b2e55b53-4ba9-4fba-865c-37041a69d178",
        "title": "Department SUNCLIPSE",
        "users": {
            "_id": 1,
            "lead": {
                "_id": 1,
                "name": "Jody Molina",
                "email": "jodymolina@sunclipse.com"
            },
            "employees": [
                {
                    "_id": 0,
                    "name": "Clements Berg",
                    "email": "clementsberg@sunclipse.com"
                },
                {
                    "_id": 1,
                    "name": "Ferguson Bass",
                    "email": "fergusonbass@sunclipse.com"
                },
                {
                    "_id": 2,
                    "name": "Tonia Olson",
                    "email": "toniaolson@sunclipse.com"
                },
                {
                    "_id": 3,
                    "name": "Anita Delacruz",
                    "email": "anitadelacruz@sunclipse.com"
                },
                {
                    "_id": 4,
                    "name": "Mercado Weber",
                    "email": "mercadoweber@sunclipse.com"
                },
                {
                    "_id": 5,
                    "name": "Cherry Hamilton",
                    "email": "cherryhamilton@sunclipse.com"
                },
                {
                    "_id": 6,
                    "name": "Baxter Church",
                    "email": "baxterchurch@sunclipse.com"
                }
            ]
        },
    },
    {
        "_id": "6119436a9daac695255223b6",
        "guid": "7509553d-3ac2-4dee-94bc-ca705c8834a5",
        "title": "Department CENTREGY",
        "users": {
            "_id": 2,
            "lead": {
                "_id": 2,
                "name": "Florence Cline",
                "email": "florencecline@centregy.com"
            },
            "employees": [
                {
                    "_id": 0,
                    "name": "Clayton Bonner",
                    "email": "claytonbonner@centregy.com"
                },
                {
                    "_id": 1,
                    "name": "Mcleod Ashley",
                    "email": "mcleodashley@centregy.com"
                },
                {
                    "_id": 2,
                    "name": "Steele Gray",
                    "email": "steelegray@centregy.com"
                },
                {
                    "_id": 3,
                    "name": "William Salinas",
                    "email": "williamsalinas@centregy.com"
                },
                {
                    "_id": 4,
                    "name": "Hampton Glass",
                    "email": "hamptonglass@centregy.com"
                }
            ]
        },
        child: [
            {
                "_id": "6119436a17bba24a0533599f",
                "guid": "d68145ac-2b4d-413b-a4fc-dd5dac8e98b0",
                "title": "Department PYRAMAX",
                "users": {
                    "_id": 3,
                    "lead": {
                        "_id": 3,
                        "name": "Rachel Mcbride",
                        "email": "rachelmcbride@pyramax.com"
                    },
                    "employees": [
                        {
                            "_id": 0,
                            "name": "Ewing Wise",
                            "email": "ewingwise@pyramax.com"
                        },
                        {
                            "_id": 1,
                            "name": "York Mcintosh",
                            "email": "yorkmcintosh@pyramax.com"
                        },
                        {
                            "_id": 2,
                            "name": "Simmons Michael",
                            "email": "simmonsmichael@pyramax.com"
                        },
                        {
                            "_id": 3,
                            "name": "Juliette Moon",
                            "email": "juliettemoon@pyramax.com"
                        },
                        {
                            "_id": 4,
                            "name": "Wood Mcclure",
                            "email": "woodmcclure@pyramax.com"
                        },
                        {
                            "_id": 5,
                            "name": "Katherine Blake",
                            "email": "katherineblake@pyramax.com"
                        }
                    ]
                },
                child: [
                    {
                        "_id": "6119436a13c630f87c05a95c",
                        "guid": "8052ddae-e8c1-47c1-812f-ced59208881d",
                        "title": "Department KINETICUT",
                        "users": {
                            "_id": 4,
                            "lead": {
                                "_id": 4,
                                "name": "Bean Alexander",
                                "email": "beanalexander@kineticut.com"
                            },
                            "employees": [
                                {
                                    "_id": 0,
                                    "name": "Amie Kinney",
                                    "email": "amiekinney@kineticut.com"
                                },
                                {
                                    "_id": 1,
                                    "name": "Edna Cook",
                                    "email": "ednacook@kineticut.com"
                                },
                                {
                                    "_id": 2,
                                    "name": "Brewer Kelly",
                                    "email": "brewerkelly@kineticut.com"
                                },
                                {
                                    "_id": 3,
                                    "name": "Sasha Baker",
                                    "email": "sashabaker@kineticut.com"
                                },
                                {
                                    "_id": 4,
                                    "name": "Robinson Hampton",
                                    "email": "robinsonhampton@kineticut.com"
                                },
                                {
                                    "_id": 5,
                                    "name": "Emily Mcmahon",
                                    "email": "emilymcmahon@kineticut.com"
                                }
                            ]
                        }
                    }
                ]
            },
        ]
    },
    ],
};
