<template>
    <div>
        <h2 class="font-weight-bold">Users</h2>
        <p class="subtitle-1">Tree practice</p>

        <CardInfo :description="description" />

        <OrgStucture :tree="tree" />
    </div>
</template>

<script lang="ts">
import { Component, Vue } from 'nuxt-property-decorator';
import { orgStructureData } from '~/types/OrgStructureMock';
// @ts-ignore
import { Tree } from '~/types/Tree.ts';
// @ts-ignore
import { OrgDepartment } from '~/types/OrgDepartment.ts';

@Component({
    head: {
        title: 'Users',
    },
    components: {
        CardInfo: () => import('~/components/ui/CardInfo.vue'),
        OrgStucture: () => import('~/components/OrgStructure/OrgStucture.vue'),
    },
})
export default class UsersTree extends Vue {
    description = `
        WIP. Practice skills: working with trees, algorithms, TypeScript, custom tree layout.
        Tasks is to show organization stucture which contains departments and employeers.
        Department can contain another departments. User of system should be able to open one node by click on it
        or open/close all stucture using toggle button.
        ALL THE DATA WAS AUTOGENERATED.
    `;

    tree: Tree | null = null;

    created() {
        this.tree = new Tree<OrgDepartment>(orgStructureData, 'child');
    }
}
</script>
